language: python
dist: bionic
sudo: true
services:
  - postgresql
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - 3.8
install:
  - pip install tox
  - pip install -q tox-travis
script:
    - tox

stages:
  - lint
  - test

jobs:
  include:
    - { stage: lint, env: TOXENV=flake8, python: 3.8 }
